### ISSUE TITLE
Part numbering

### ISSUE THREAD

**Issue by dlschwartz** [jedwardwalters/SEC-test#4]
The numbering on the `<div1 type="part" n="x">` should correspond to the part of the overall work. So, Demonstration 1 should be n="1" and Demonstration 2 should be n="2". This will allow Winona to correctly order the parts. This does raise the question of what to do with that "Letter" that preceeds the first Demonstration. For now, you might want to give it n="0" and we'll figure it out from there.

**Comment by jedwardwalters** [comment]
Done.
